// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpyymmuzatcrabrsqebx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweXltbXV6YXRjcmFicnNxZWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTk0MjQsImV4cCI6MjA2MTA5NTQyNH0.Fb1G6YdNFVnYR2s0cvT0QX6pl-KH08aMVkOn4BEvtIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);